### ISSUE TITLE
[BUG] - Adding second image overwrites all images

### ISSUE THREAD

**Issue by ewanhowell5195** [Faithful-Resource-Pack/App#80] opened 2022-07-07 20:30 UTC
If you add an image in the Add-on uploader, then try to add a second image after adding the first one, instead of adding a second image, it completely replaces any images already there.

**Comment by TheRolfFR** [comment] 2022-08-13 09:34
Is it on a new add-on or an existing add-on?

**Comment by ewanhowell5195** [comment] 2022-08-20 23:38
Any

**Comment by TheRolfFR** [comment] 2022-08-21 12:06
@ewanhowell5195 I made some changes. Tell me if it still happens.

If so, could you give me details, give me the process to reproduce the bug, give me screenshots of the page, and maybe console and network tabs in developer tool?

Close the issue if you feel like it's resolved

**Comment by TheRolfFR** [comment] 2023-08-22 19:27
Fixed in 75ac31d, tell me if you like it

**Comment by 3vorp** [comment] 2024-06-02 18:07
I just tried it and it seems to be working fine now, plus there haven't been any complaints with this issue in a very long time, so I'm closing it as complete now.

**Closed by 3vorp** 2024-06-02 18:07 UTC
Labels: bug, difficulty easy, normal priority
