### ISSUE TITLE
[BUG] Switching from Light to Dark theme doesn't properly change all elements

### ISSUE THREAD

**Issue by Pomi108** [Faithful-Resource-Pack/App#53] opened 2022-04-24 07:47 UTC
**Describe the bug**
When using light theme and then switching to dark, some elements remain light.

**To Reproduce**
Steps to reproduce the behaviour:
1. Have your theme set to Light as a starting point (make sure to refresh while using it)
2. Set your theme to dark
3. See that some elements aren't being changed
4. Refresh
5. The theme is now applied properly

**Screenshots**
![Snímek obrazovky 2022-04-24 v 9 47 14](https://user-images.githubusercontent.com/59484948/164965985-1518e21a-7b37-44a5-b285-0d5c8dcd463b.png)

**Additional context**
This doesn't happen every time for some reason. But it occurs more often than not.
It also doesn't happen in reverse – switching from Dark to Light theme seems to happen properly every time.

**Comment by TheRolfFR** [comment] 2022-04-24 14:09
SHould have been fixed with b5e7331501e4b7e05c311a4c6065fe2fa00a60f2, wait a few days and tell me if you get it again

**Comment by RobertRR11** [comment] 2022-05-08 20:30
I can't reproduce the issue anymore, so I guess it was fixed by that commit. Closing now

**Closed by RobertRR11** 2022-05-08 20:30 UTC
Labels: bug

**Comment by Pomi108** [comment] 2022-05-08 20:34
Yeah this was fixed, forgot to close this
