### ISSUE TITLE
[BUG] Gallery doesn't load additional textures at all

### ISSUE THREAD

**Issue by Pomi108** [Faithful-Resource-Pack/App#54] opened 2022-04-24 10:38 UTC
**Describe the bug**
When using a page scale other than 100% (for example 110% or 90%) and searching for something like `potion_bottle` in bedrock (which doesn't display all results immediately and instead loads them when you scroll to the bottom of the page), the additional textures don't load. This applies when searching for all textures (without a search query) as well.

**To Reproduce**
Steps to reproduce the behaviour:
1. ~~Set your browser scale to anything other than 100%~~ (now happens on all scales)
2. Go to the gallery
3. Don't search for anything, just leave it on All
4. Scroll to the bottom of the page
5. See that additional textures aren't being loaded

**Screenshots**
![Snímek obrazovky 2022-04-24 v 12 35 53](https://user-images.githubusercontent.com/59484948/164972424-f2759f95-dac8-4f70-8c18-bfd28cee0935.png)

**Browser & Environment (computer/phone):**
 - Firefox
 - 99.0.1

**Additional context**
If you set your browser scale to 100%, the textures start being loaded immediately (and inversely, when setting it back to something other than 100%, they stop being loaded), no refreshing is required.

**Comment by Pomi108** [comment] 2022-04-28 15:27
Update – the gallery no longer loads additional textures at all, not even on the regular scale of 100%.

**Comment by Pomi108** [comment] 2022-04-28 15:30
Update 2 – The gallery manages to load the textures when setting your scale to something other than 100% then reverting back to 100%.

**Comment by RobertRR11** [comment] 2022-04-28 22:28
> Update – the gallery no longer loads additional textures at all, not even on the regular scale of 100%.

I can't reproduce this one, only the issue with scaling over or under 100%

**Comment by TheRandomGamrTRG** [comment] 2022-05-03 14:29
In my experience, the page won't load more textures, until I change zoom level to something other than 100, and then return it to 100. At this point the vertical main menu opens by itself ( it was closed before) and new textures will load when scrolling down. Closing the menu will break it again.

**Closed** 2022-05-07 16:44 UTC
Labels: bug, high priority
